"""journal entries and emotions

Revision ID: 9aefe6cf3159
Revises: 626f272bb010
Create Date: 2026-08-10 21:56:15.346692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aefe6cf3159'
down_revision: Union[str, Sequence[str], None] = '626f272bb010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('mood_score', sa.Integer(), nullable=True),
    sa.Column('energy_level', sa.Integer(), nullable=True),
    sa.Column('stress_level', sa.Integer(), nullable=True),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.Column('mood_influence', sa.Text(), nullable=True),
    sa.Column('did_sport', sa.Boolean(), nullable=False),
    sa.Column('sport_type', sa.String(length=100), nullable=True),
    sa.Column('sport_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('had_sex', sa.Boolean(), nullable=False),
    sa.Column('cried', sa.Boolean(), nullable=False),
    sa.Column('had_headache', sa.Boolean(), nullable=False),
    sa.Column('had_pain', sa.Boolean(), nullable=False),
    sa.Column('pain_level', sa.Integer(), nullable=True),
    sa.Column('pain_location', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('gratitude', sa.Text(), nullable=True),
    sa.Column('positive_event', sa.Text(), nullable=True),
    sa.Column('negative_event', sa.Text(), nullable=True),
    sa.Column('reflection', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'entry_date', name='uq_journal_user_date')
    )
    op.create_index(op.f('ix_journal_entries_entry_date'), 'journal_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_journal_entries_user_id'), 'journal_entries', ['user_id'], unique=False)
    op.create_table('journal_entry_emotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_entry_id', sa.Integer(), nullable=False),
    sa.Column('emotion_id', sa.Integer(), nullable=False),
    sa.Column('intensity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['emotion_id'], ['emotions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journal_entry_id', 'emotion_id', name='uq_entry_emotion')
    )
    op.create_index(op.f('ix_journal_entry_emotions_journal_entry_id'), 'journal_entry_emotions', ['journal_entry_id'], unique=False)
    # ### end Alembic commands ###

    # Seed the global emotion catalog
    from app.database.seed import DEFAULT_EMOTIONS

    emotions_table = sa.table(
        "emotions", sa.column("name", sa.String), sa.column("emoji", sa.String)
    )
    op.bulk_insert(emotions_table, DEFAULT_EMOTIONS)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journal_entry_emotions_journal_entry_id'), table_name='journal_entry_emotions')
    op.drop_table('journal_entry_emotions')
    op.drop_index(op.f('ix_journal_entries_user_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_entry_date'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_table('emotions')
    # ### end Alembic commands ###
